spring.main.banner-mode=off
spring.jackson.default-property-inclusion=non_null
logging.level.io.spring.github.actions.artifactorydeploy=warn
spring.http.clients.connect-timeout=1m
spring.http.clients.read-timeout=5m
